language: csharp
solution: Tik.Travis.sln
dotnet: 2.0.0
dist: trusty
addons:
  sonarcloud:
    organization: sripirom-github
    token:
      secure: eNifKA4SZMFYHfX9ciaN868VKqjeALVv+yRTg6vXndidYH1plmjddtrHZ+2eDdGQa43e5DsHkrNj8yGaL2pj3Rqhndiyw3VIVKd/H2MzoYzNuPsCGZXavUJBDzkQwTpEtKJTNBAFqhZr0OYQJByDbXVPmRw9SaBQKCsmkPbv4vktpopXqyYAi637sB9x+A9di/MAEZ2rlPOGZqhJxh+23Ry4yaIml2lW/a8soXN0AhVeKkd0+2tNK7TP05jJDCqNN5/0oIFsFNmqODQvQ0PGc7lxe1+piTHa7JHQfxSWe0/OVnz64ajOuhbkssnFcv4UkcXJ5m4V5snimrM3t0IIqd+y4hmKYcLaqGaAZxVba6jPoCJ6otGLMcOMnNvKsiVl+0fITwYTPU0lPsF9zCc0+w8CEUdD3EOxjoo48hMLV5RwtlwjOOZkPjYM0wnOun5s0BWISvQ98QrZVATeT6wIKLSvdtpVARZFqPy4E/mBbFCsbqFi/djpet0psXe6NXvRcflIJRVsEX4SPulrX76O8ttJvLpDRqFEApWKEQdxHQanTmVycRCNNWGoF4xADg1bhBapSrAhJnHzNiQT8SUkKBJiEyXiEHT0IuqDLu6LFKpexSnOi7brHwmx3lImxiJMYwork9kO3NrZy5fFWy+BeemDgmPD6MkE3DG1dtusIoQ=
    branches:
    - master
    - develop
install:
- dotnet restore ./app/
- wget https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.0.2.892/sonar-scanner-msbuild-4.0.2.892.zip
- unzip sonar-scanner-msbuild-4.0.2.892.zip
script:
- mono SonarQube.Scanner.MSBuild.exe begin /k:"tik_travis-master" /n:"tik_travis" /v:"1.0.0" /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=%SONAR_TOKEN% /d:"sonar.organization=sripirom-github"
- dotnet build ./app/Tik.Travis.sln -c Release -f netcoreapp2.0
- dotnet test ./app/Tik.Travis.Lib.Tests/Tik.Travis.Lib.Tests.csproj
- mono SonarQube.Scanner.MSBuild.exe end /d:sonar.login=%SONAR_TOKEN%

