language: csharp
solution: Tik.Travis.sln
dotnet: 2.0.0
dist: trusty
env:
  SONAR_SCANNER_HOME=/home/travis/build/sripirom/T-I-K_Travis
addons:
  artifacts:
    debug: true
  sonarcloud:
    organization: sripirom-github
    token:
      secure: $SONAR_TOKEN
    branches:
    - master
    - develop
install:
  - dotnet restore ./app/
  - wget https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.0.2.892/sonar-scanner-msbuild-4.0.2.892.zip
  - unzip sonar-scanner-msbuild-4.0.2.892.zip
script: sh sonarbuild.sh
