language: csharp
solution: Tik.Travis.sln
mono: none
dotnet: 2.0.0
dist: trusty
addons:
  artifacts:
    debug: true
  sonarcloud:
    organization: sripirom-github
    token:
      secure: $SONAR_TOKEN
    branches:
    - master
    - develop
script:
- sonar-scanner

