language: csharp
solution: Tik.Travis.sln
dotnet: 2.0.0
dist: trusty
mono: none
env:
  SONAR_SCANNER_HOME=/home/travis/build/sripirom/sonar-scanner-msbuild
install:
  - wget https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.0.2.892/sonar-scanner-msbuild-4.0.2.892.zip
  - unzip sonar-scanner-msbuild-4.0.2.892.zip $SONAR_SCANNER_HOME
script:   
  - ls
