language: csharp
solution: Tik.Travis.sln
mono: none
dotnet: 2.0
script:    # the following commands are just examples, use whatever your build process requires
  - dotnet restore
  - dotnet build ./app/Tik.Travis.sln -c Release -f netcoreapp1.0
