language: csharp
solution: Tik.Travis.sln
dotnet: 2.0.0
dist: trusty
addons:
  artifacts:
    debug: true
  sonarcloud:
    organization: sripirom-github
    token:
      secure: xkqa9I3e1OflxZ7m2UWe2IWyRfELge/xK8WfONRbPH9XYLOwdRhP5uJfan5WcgRdS4KExJUf9cm/F9frSUwCxxZOEIR8NQYaIwlgJ28FJyOQflEalVoXfs79B9CHRwx+yexANLQ/1rotTMsSzikETzAn+ItL+POzMVbtn0a+bpBfFsnEBfswNmlLUZzktZ0M9dn56ON/Ns3Y0nKp1yTkZ3JreZhlqTM1GMkzernbR9GvbiCWG4RlsHooDQHtEkpxheE3eI1PLM7OKkbXN1+2HqMmg0pXicDrsekXtZTcHXaQn5/GgL04mz0c/r5eJ2gtb6qU4rmJ5VuScIRHwzSDq7tsyGk6gdFAgJryG0azeF8pl9zwyM1wK4CYhD16g0/6Uqhi+SHPLTuriNx+21ENuFHSHpurBoHBEcWEZ4mktNB5l3SkNPX1+6EoBBpoMFWoxqn1Kep5RHgMq4NmJ/MXfDa1YPfobn4wi6Xr6o8uEH1imbjxsORlNrs2Xi/E5uSH8k4fCwOgXkzhSujXbnBxXdzxro2twoN8p4I6zIdyEJlZld+9VB9y9OcvMxC0LGco39JTICQ+JwUCcAVsdbN3FMX2Ep49IpqazBGPVOj71PjhSsv1ZvgdT+qagadRstREDjxa8QemOfrX57IbV+VgY/ZOpLUfyJt27krPH5xKVCU=
    branches:
    - master
    - develop
install:
- dotnet restore ./app/
- wget https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.0.2.892/sonar-scanner-msbuild-4.0.2.892.zip
- unzip sonar-scanner-msbuild-4.0.2.892.zip
script:
- echo $SONAR_TOKEN
- mono SonarQube.Scanner.MSBuild.exe begin /k:"tik_travis-master" /n:"tik_travis" /v:"1.0.0" /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=$SONAR_TOKEN /d:"sonar.organization=sripirom-github"
- dotnet build ./app/Tik.Travis.sln -c Release -f netcoreapp2.0
- dotnet test ./app/Tik.Travis.Lib.Tests/Tik.Travis.Lib.Tests.csproj
- mono SonarQube.Scanner.MSBuild.exe end /d:sonar.login=$SONAR_TOKEN
