language: csharp
solution: Tik.Travis.sln
mono: none
dotnet: 2.0.0
dist: trusty
addons:
  apt:
    sources:
    - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod
        trusty main
      key_url: https://packages.microsoft.com/keys/microsoft.asc
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5

install:
  - dotnet restore ./app/

script:
  - dotnet build ./app/Tik.Travis.sln -c Release -f netcoreapp2.0
  - sonar-scanner -X
script:
 - dotnet build ./app/Tik.Travis.sln -c Release -f netcoreapp2.0
 - dotnet test ./app/Tik.Travis.Lib.Tests/Tik.Travis.Lib.Tests.csproj
notifications:
  email: false
